znrc = [
"Adventure Awaits",
"Akoum Hellhound",
"Angelheart Protector",
"Anticognition",
"Ardent Electromancer",
"Blood Beckoning",
"Blood Price",
"Broken Wings",
"Bubble Snare",
"Canopy Baloth",
"Cascade Seer",
"Chilling Trap",
"Cleansing Wildfire",
"Cleric of Chill Depths",
"Cliffhaven Kitesail",
"Cliffhaven Sell-Sword",
"Cunning Geysermage",
"Dauntless Survivor",
"Dauntless Unity",
"Deadly Alliance",
"Deliberate",
"Disenchant",
"Drana's Silencer",
"Dreadwurm",
"Expedition Champion",
"Expedition Diviner",
"Expedition Healer",
"Expedition Skulker",
"Farsight Adept",
"Feed the Swarm",
"Field Research",
"Fissure Wizard",
"Ghastly Gloomhunter",
"Glacial Grasp",
"Gnarlid Colony",
"Grotag Bug-Catcher",
"Guul Draz Mucklord",
"Hagra Constrictor",
"Highborn Vampire",
"Inordinate Rage",
"Into the Roil",
"Joraga Visionary",
"Kabira Outrider",
"Kazandu Nectarpot",
"Kazandu Stomper",
"Kor Celebrant",
"Living Tempest",
"Makindi Ox",
"Malakir Blood-Priest",
"Marauding Blight-Priest",
"Mesa Lynx",
"Might of Murasa",
"Mind Drain",
"Molten Blast",
"Murasa Brute",
"Nahiri's Binding",
"Negate",
"Nimana Skitter-Sneak",
"Nimana Skydancer",
"Nissa's Zendikon",
"Oblivion's Hunger",
"Practiced Tactics",
"Pressure Point",
"Prowling Felidar",
"Pyroclastic Hellion",
"Rabid Bite",
"Reclaim the Wastes",
"Resolute Strike",
"Risen Riptide",
"Roil Eruption",
"Scale the Heights",
"Scavenged Blade",
"Scorch Rider",
"Seafloor Stalker",
"Sea Gate Banneret",
"Sea Gate Colossus",
"Shell Shield",
"Shepherd of Heroes",
"Sizzling Barrage",
"Skyclave Sentinel",
"Skyclave Squid",
"Smite the Monstrous",
"Sneaking Guide",
"Spare Supplies",
"Spitfire Lagac",
"Stonework Packbeast",
"Strength of Solidarity",
"Subtle Strike",
"Synchronized Spellcraft",
"Tajuru Blightblade",
"Tajuru Snarecaster",
"Tazeem Raptor",
"Tazeem Roilmage",
"Teeterpeak Ambusher",
"Territorial Scythecat",
"Tormenting Voice",
"Tuktuk Rubblefort",
"Turntimber Ascetic",
"Utility Knife",
"Vanquish the Weak",
"Zulaport Duelist",
];

znru = [
"Acquisitions Expert",
"Akoum Warrior",
"Allied Assault",
"Attended Healer",
"Bala Ged Recovery",
"Base Camp",
"Beyeen Veil",
"Blackbloom Rogue",
"Bloodchief's Thirst",
"Brushfire Elemental",
"Canyon Jerboa",
"Cinderclasm",
"Cleric of Life's Bond",
"Concerted Defense",
"Demon's Disciple",
"Emeria Captain",
"Fearless Fledgling",
"Fireblade Charger",
"Goma Fada Vanguard",
"Grotag Night-Runner",
"Iridescent Hornbeetle",
"Journey to Oblivion",
"Jwari Disruption",
"Kabira Takedown",
"Kargan Warleader",
"Kazuul's Fury",
"Khalni Ambush",
"Kitesail Cleric",
"Kor Blademaster",
"Lithoform Blight",
"Lullmage's Domination",
"Lullmage's Familiar",
"Makindi Stampede",
"Malakir Rebirth",
"Merfolk Falconer",
"Merfolk Windrobber",
"Mind Carver",
"Moss-Pit Skeleton",
"Murasa Rootgrazer",
"Murasa Sproutling",
"Paired Tactician",
"Pelakka Predation",
"Ravager's Mace",
"Relic Amulet",
"Relic Axe",
"Relic Golem",
"Relic Vial",
"Rockslide Sorcerer",
"Roiling Regrowth",
"Roost of Drakes",
"Ruin Crab",
"Scion of the Swarm",
"Sejiri Shelter",
"Shadow Stinger",
"Shatterskull Minotaur",
"Silundi Vision",
"Skyclave Cleric",
"Skyclave Geopede",
"Skyclave Pick-Axe",
"Skyclave Plunder",
"Skyclave Shadowcat",
"Soaring Thought-Thief",
"Song-Mad Treachery",
"Spikefield Hazard",
"Spoils of Adventure",
"Springmantle Cleric",
"Sure-Footed Infiltrator",
"Tangled Florahedron",
"Taunting Arbormage",
"Thundering Rebuke",
"Thundering Sparkmage",
"Thwart the Grave",
"Umara Mystic",
"Umara Wizard",
"Vastwood Fortification",
"Vastwood Surge",
"Veteran Adventurer",
"Vine Gecko",
"Windrider Wizard",
"Zof Consumption",
];

khmc = [
"Alpine Meadow",
"Annul",
"Arachnoform",
"Arctic Treeline",
"Augury Raven",
"Axgard Braggart",
"Axgard Cavalry",
"Battlefield Raptor",
"Behold the Multiverse",
"Berg Strider",
"Beskir Shieldmate",
"Bind the Monster",
"Bound in Gold",
"Breakneck Berserker",
"Brinebarrow Intruder",
"Broken Wings",
"Cinderheart Giant",
"Codespell Cleric",
"Craven Hulk",
"Deathknell Berserker",
"Demon Bolt",
"Demonic Gifts",
"Depart the Realm",
"Disdainful Stroke",
"Dogged Pursuit",
"Doomskar Oracle",
"Draugr Recruiter",
"Draugr Thought-Thief",
"Dread Rider",
"Duskwielder",
"Dwarven Reinforcements",
"Elderfang Disciple",
"Elderleaf Mentor",
"Fearless Pup",
"Feed the Serpent",
"Frost Bite",
"Frostpeak Yeti",
"Funeral Longboat",
"Giant Ox",
"Glacial Floodplain",
"Glittering Frost",
"Gnottvold Recluse",
"Gods' Hall Guardian",
"Goldmaw Champion",
"Goldvein Pick",
"Grim Draugr",
"Grizzled Outrider",
"Guardian Gladewalker",
"Hagi Mob",
"Highland Forest",
"Horizon Seeker",
"Icehide Troll",
"Ice Tunnel",
"Immersturm Raider",
"Infernal Pet",
"Invoke the Divine",
"Iron Verdict",
"Jarl of the Forsaken",
"Jaspera Sentinel",
"Karfell Harbinger",
"Karfell Kennel-Master",
"King Harald's Revenge",
"Koma's Faithful",
"Littjara Kinseekers",
"Mammoth Growth",
"Masked Vandal",
"Master Skald",
"Mists of Littjara",
"Mistwalker",
"Open the Omenpaths",
"Pilfering Hawk",
"Priest of the Haunted Edge",
"Raiders' Karve",
"Raise the Draugr",
"Ravenform",
"Ravenous Lindwurm",
"Raven Wings",
"Revitalize",
"Rimewood Falls",
"Roots of Wisdom",
"Run Amok",
"Run Ashore",
"Sarulf's Packmate",
"Scorn Effigy",
"Sculptor of Winter",
"Seize the Spoils",
"Shackles of Treachery",
"Shimmerdrift Vale",
"Skull Raid",
"Smashing Success",
"Snakeskin Veil",
"Snowfield Sinkhole",
"Squash",
"Stalwart Valkyrie",
"Starnheim Courser",
"Story Seeker",
"Strategic Planning",
"Struggle for Skemfar",
"Sulfurous Mire",
"Tormentor's Helm",
"Tuskeri Firewalker",
"Undersea Invader",
"Valor of the Worthy",
"Vault Robber",
"Village Rites",
"Volatile Fjord",
"Warhorn Blast",
"Weigh Down",
"Wings of the Cosmos",
"Withercrown",
"Woodland Chasm",
];

khmu = [
"Absorb Identity",
"Aegar, the Freezing Flame",
"Armed and Armored",
"Arni Slays the Troll",
"Ascent of the Worthy",
"Avalanche Caller",
"Axgard Armory",
"Basalt Ravager",
"Battershield Warrior",
"Bearded Axe",
"Binding the Old Gods",
"Blizzard Brawl",
"Bloodline Pretender",
"Bloodsky Berserker",
"Boreal Outrider",
"Bretagard Stronghold",
"Clarion Spirit",
"Colossal Plow",
"Crush the Weak",
"Divine Gambit",
"Doomskar Titan",
"Draugr's Helm",
"Dual Strike",
"Dwarven Hammer",
"Elderfang Ritualist",
"Elven Ambush",
"Elven Bow",
"Fall of the Impostor",
"Fearless Liberator",
"Fire Giant's Fury",
"Firja, Judge of Valor",
"Forging the Tyrite Sword",
"Frenzied Raider",
"Frost Augur",
"Frostpyre Arcanist",
"Fynn, the Fangbearer",
"Gates of Istfell",
"Giant's Amulet",
"Giant's Grasp",
"Gilded Assault Cart",
"Gladewalker Ritualist",
"Glimpse the Cosmos",
"Gnottvold Slumbermound",
"Great Hall of Starnheim",
"Hailstorm Valkyrie",
"Harald, King of Skemfar",
"Icebind Pillar",
"Immersturm Skullcairn",
"Inga Rune-Eyes",
"Invasion of the Giants",
"Kardur, Doomscourge",
"Kardur's Vicious Return",
"Kaya's Onslaught",
"Koll, the Forgemaster",
"Littjara Glade-Warden",
"Littjara Mirrorlake",
"Maja, Bretagard Protector",
"Moritte of the Frost",
"Narfi, Betrayer King",
"Niko Defies Destiny",
"Path to the World Tree",
"Poison the Cup",
"Port of Karfell",
"Provoke the Trolls",
"Rampage of the Valkyries",
"Renegade Reaper",
"Replicating Ring",
"Return Upon the Tide",
"Rootless Yew",
"Runed Crown",
"Rune of Flight",
"Rune of Might",
"Rune of Mortality",
"Rune of Speed",
"Rune of Sustenance",
"Saw It Coming",
"Shepherd of the Cosmos",
"Skemfar Elderhall",
"Skemfar Shadowsage",
"Spectral Steel",
"Spirit of the Aldergard",
"Starnheim Aspirant",
"Surtland Frostpyre",
"Svella, Ice Shaper",
"Tergrid's Shadow",
"The Three Seasons",
"The Trickster-God's Heist",
"Thornmantle Striker",
"Usher of the Fallen",
"Valkyrie's Sword",
"Vega, the Watcher",
"Vengeful Reaper",
"Warchanter Skald",
"Weathered Runestone",
"Youthful Valkyrie",
];

stxc = [
"Ageless Guardian",
"Arcane Subtraction",
"Archway Commons",
"Arrogant Poet",
"Bayou Groff",
"Beaming Defiance",
"Biblioplex Assistant",
"Big Play",
"Biomathematician",
"Blood Age General",
"Blood Researcher",
"Burrog Befuddler",
"Bury in Books",
"Campus Guide",
"Charge Through",
"Cogwork Archivist",
"Combat Professor",
"Cram Session",
"Crushing Disappointment",
"Curate",
"Defend the Campus",
"Dragon's Approach",
"Eager First-Year",
"Elemental Masterpiece",
"Elemental Summoning",
"Enthusiastic Study",
"Environmental Sciences",
"Essence Infusion",
"Eureka Moment",
"Excavated Wall",
"Exhilarating Elocution",
"Expanded Anatomy",
"Expel",
"Field Trip",
"First Day of Class",
"Fractal Summoning",
"Frost Trickster",
"Fuming Effigy",
"Guiding Voice",
"Heated Debate",
"Hunt for Specimens",
"Illustrious Historian",
"Infuse with Vitality",
"Inkling Summoning",
"Introduction to Annihilation",
"Introduction to Prophecy",
"Lash of Malice",
"Leech Fanatic",
"Letter of Acceptance",
"Leyline Invocation",
"Lorehold Campus",
"Lorehold Pledgemage",
"Mage Duel",
"Mage Hunters' Onslaught",
"Make Your Mark",
"Moldering Karok",
"Needlethorn Drake",
"Novice Dissector",
"Oggyar Battle-Seer",
"Owlin Shieldmage",
"Pest Summoning",
"Pigment Storm",
"Pilgrim of the Ages",
"Pillardrop Rescuer",
"Pillardrop Warden",
"Pop Quiz",
"Prismari Campus",
"Prismari Pledgemage",
"Professor of Zoomancy",
"Professor's Warning",
"Promising Duskmage",
"Quandrix Campus",
"Quandrix Pledgemage",
"Reckless Amplimancer",
"Reject",
"Relic Sloth",
"Resculpt",
"Rise of Extus",
"Scurrid Colony",
"Serpentine Curve",
"Silverquill Campus",
"Silverquill Pledgemage",
"Soothsayer Adept",
"Spectacle Mage",
"Specter of the Fens",
"Spined Karok",
"Spirit Summoning",
"Spiteful Squad",
"Springmane Cervin",
"Square Up",
"Star Pupil",
"Stonebound Mentor",
"Stonerise Spirit",
"Study Break",
"Sudden Breakthrough",
"Tangletrap",
"Teach by Example",
"Thrilling Discovery",
"Tome Shredder",
"Twinscroll Shaman",
"Unwilling Ingredient",
"Vortex Runner",
"Waterfall Aerialist",
"Witherbloom Campus",
"Witherbloom Pledgemage",
];

stxu = [
"Academic Dispute",
"Access Tunnel",
"Aether Helix",
"Ardent Dustspeaker",
"Bookwurm",
"Brackish Trudge",
"Clever Lumimancer",
"Closing Statement",
"Containment Breach",
"Creative Outburst",
"Daemogoth Woe-Eater",
"Deadly Brew",
"Decisive Denial",
"Detention Vortex",
"Devouring Tendrils",
"Dina, Soul Steeper",
"Dueling Coach",
"Emergent Sequence",
"Explosive Welcome",
"Expressive Iteration",
"Eyetwitch",
"Flunk",
"Fortifying Draught",
"Fracture",
"Go Blank",
"Golden Ratio",
"Grinning Ignus",
"Hall Monitor",
"Honor Troll",
"Humiliate",
"Igneous Inspiration",
"Karok Wrangler",
"Kelpie Guide",
"Killian, Ink Duelist",
"Lorehold Apprentice",
"Lorehold Excavation",
"Maelstrom Muse",
"Mage Hunter",
"Mascot Interception",
"Master Symmetrist",
"Mentor's Guidance",
"Mercurial Transformation",
"Mortality Spear",
"Necrotic Fumes",
"Overgrown Arch",
"Plumb the Forbidden",
"Practical Research",
"Prismari Apprentice",
"Professor of Symbology",
"Quandrix Apprentice",
"Quandrix Cultivator",
"Quintorius, Field Historian",
"Reconstruct History",
"Reduce to Memory",
"Reflective Golem",
"Returned Pastcaller",
"Rip Apart",
"Rootha, Mercurial Artist",
"Secret Rendezvous",
"Shadewing Laureate",
"Show of Confidence",
"Silverquill Apprentice",
"Snow Day",
"Solve the Equation",
"Spell Satchel",
"Start from Scratch",
"Stonebinder's Familiar",
"Storm-Kiln Artist",
"Symmetry Sage",
"Team Pennant",
"Tend the Pests",
"Tenured Inkcaster",
"Test of Talents",
"Thunderous Orator",
"Umbral Juke",
"Witherbloom Apprentice",
"Wormhole Serpent",
"Zephyr Boots",
"Zimone, Quandrix Prodigy",
"Adventurous Impulse",
"Agonizing Remorse",
"Claim the Firstborn",
"Cultivate",
"Defiant Strike",
"Divine Gambit",
"Duress",
"Eliminate",
"Infuriate",
"Negate",
"Opt",
"Revitalize",
"Shock",
"Snakeskin Veil",
"Strategic Planning",
"Thrill of Possibility",
"Village Rites",
"Whirlwind Denial",
];

afrc = [
"+2 Mace",
"Air-Cult Elemental",
"Arborea Pegasus",
"Arcane Investigator",
"Armory Veteran",
"Baleful Beholder",
"Bar the Gate",
"Boots of Speed",
"Brazen Dwarf",
"Bulette",
"Bull's Strength",
"Celestial Unicorn",
"Charmed Sleep",
"Circle of the Moon Druid",
"Clattering Skeletons",
"Clever Conjurer",
"Compelled Duel",
"Contact Other Plane",
"Dawnbringer Cleric",
"Deadly Dispute",
"Delver's Torch",
"Devoted Paladin",
"Devour Intellect",
"Dire Wolf Prowler",
"Djinni Windseer",
"Dragon's Fire",
"Dueling Rapier",
"Dwarfhold Champion",
"Earth-Cult Elemental",
"Elturgard Ranger",
"Evolving Wilds",
"Eyes of the Beholder",
"Farideh's Fireball",
"Fates' Reversal",
"Feign Death",
"Find the Path",
"Gloom Stalker",
"Gnoll Hunter",
"Goblin Javelineer",
"Greataxe",
"Grim Bounty",
"Half-Elf Monk",
"Herald of Hadar",
"Hill Giant Herdgorger",
"Hired Hexblade",
"Hoarding Ogre",
"Hoard Robber",
"Hobgoblin Captain",
"Improvised Weaponry",
"Inspiring Bard",
"Jaded Sell-Sword",
"Kick in the Door",
"Leather Armor",
"Manticore",
"Mimic",
"Minimus Containment",
"Mordenkainen's Polymorph",
"Neverwinter Dryad",
"Owlbear",
"Paladin's Shield",
"Pixie Guide",
"Planar Ally",
"Plummet",
"Plundering Barbarian",
"Potion of Healing",
"Precipitous Drop",
"Price of Loyalty",
"Priest of Ancient Lore",
"Ranger's Hawk",
"Ranger's Longbow",
"Rimeshield Frost Giant",
"Scaled Herbalist",
"Scion of Stygia",
"Secret Door",
"Sepulcher Ghoul",
"Shambling Ghast",
"Shocking Grasp",
"Shortcut Seeker",
"Silver Raven",
"Soulknife Spy",
"Spare Dagger",
"Spiked Pit Trap",
"Spoils of the Hunt",
"Steadfast Paladin",
"Swarming Goblins",
"Sylvan Shepherd",
"Thieves' Tools",
"Underdark Basilisk",
"Unexpected Windfall",
"Valor Singer",
"Vampire Spawn",
"Veteran Dungeoneer",
"You Come to a River",
"You Come to the Gnoll Camp",
"You Find a Cursed Idol",
"You Find the Villains' Lair",
"You Hear Something on Watch",
"You're Ambushed on the Road",
"You See a Guard Approach",
"Yuan-Ti Fang-Blade",
"Zombie Ogre",
];

afru = [
"Aberrant Mind Sorcerer",
"Bag of Holding",
"Barbarian Class",
"Barrowin of Clan Undurr",
"Battle Cry Goblin",
"Black Dragon",
"Blink Dog",
"Blue Dragon",
"Bruenor Battlehammer",
"Burning Hands",
"Chaos Channeler",
"Check for Traps",
"Choose Your Weapon",
"Cleric Class",
"Cloister Gargoyle",
"Critical Hit",
"Death-Priest of Myrkul",
"Demogorgon's Clutches",
"Displacer Beast",
"Divine Smite",
"Dragon's Disciple",
"Drider",
"Druid Class",
"Dungeon Crawler",
"Dungeon Map",
"Eccentric Apprentice",
"Farideh, Devil's Chosen",
"Feywild Trickster",
"Fifty Feet of Rope",
"Fly",
"Goblin Morningstar",
"Green Dragon",
"Gretchen Titchwillow",
"Grim Wanderer",
"Guild Thief",
"Hama Pashar, Ruin Seeker",
"Hulking Bugbear",
"Hunter's Mark",
"Ingenious Smith",
"Intrepid Outlander",
"Iron Golem",
"Kalain, Reclusive Painter",
"Keen-Eared Sentry",
"Krydle of Baldur's Gate",
"Lightfoot Rogue",
"Loathsome Troll",
"Lurking Roper",
"Magic Missile",
"Monk of the Open Hand",
"Moon-Blessed Cleric",
"Plate Armor",
"Portable Hole",
"Power of Persuasion",
"Power Word Kill",
"Prosperous Innkeeper",
"Purple Worm",
"Rally Maneuver",
"Ray of Enfeeblement",
"Ray of Frost",
"Reaper's Talisman",
"Red Dragon",
"Rust Monster",
"Shessra, Death's Whisper",
"Skullport Merchant",
"Split the Party",
"Sudden Insight",
"Targ Nar, Demon-Fang Gnoll",
"Temple of the Dragon Queen",
"Tiger-Tribe Hunter",
"Trelasarra, Moon Dancer",
"Trickster's Talisman",
"Wandering Troubadour",
"Warlock Class",
"White Dragon",
"Wild Shape",
"Wizard Class",
"You Find Some Prisoners",
"You Happen On a Glade",
"You Meet in a Tavern",
"You See a Pair of Goblins",
];

midc = [
"Abandon the Post",
"Ardent Elementalist",
"Arrogant Outlaw",
"Baithook Angler",
"Bat Whisperer",
"Bird Admirer",
"Bladebrand",
"Blessed Defiance",
"Blood Pact",
"Bounding Wolf",
"Bramble Armor",
"Brimstone Vandal",
"Burn the Accursed",
"Candlegrove Witch",
"Candlelit Cavalry",
"Candletrap",
"Cathar Commando",
"Celestus Sanctifier",
"Clarion Cathars",
"Component Collector",
"Consider",
"Crawl from the Cellar",
"Crossroads Candleguide",
"Dawnhart Rejuvenator",
"Defenestrate",
"Devious Cover-Up",
"Diregraf Horde",
"Drownyard Amalgam",
"Duel for Dominance",
"Duress",
"Eaten Alive",
"Eccentric Farmer",
"Ecstatic Awakener",
"Electric Revelation",
"Evolving Wilds",
"Falcon Abomination",
"Falkenrath Perforator",
"Famished Foragers",
"Festival Crasher",
"Flare of Faith",
"Flip the Switch",
"Galedrifter",
"Gavony Silversmith",
"Gavony Trapper",
"Geistwave",
"Harvesttide Infiltrator",
"Harvesttide Sentry",
"Hedgewitch's Mask",
"Hobbling Zombie",
"Homestead Courage",
"Howl of the Hunt",
"Immolation",
"Jack-o'-Lantern",
"Lambholt Harrier",
"Larder Zombie",
"Locked in the Cemetery",
"Lunarch Veteran",
"Might of the Old Ways",
"Moonrager's Slash",
"Morkrut Behemoth",
"Mounted Dreadknight",
"Mourning Patrol",
"Neonate's Rush",
"Novice Occultist",
"No Way Out",
"Olivia's Midnight Ambush",
"Organ Hoarder",
"Otherworldly Gaze",
"Pack's Betrayal",
"Path to the Festival",
"Pestilent Wolf",
"Plummet",
"Raze the Effigy",
"Return to Nature",
"Revenge of the Drowned",
"Ritual Guardian",
"Rotten Reunion",
"Search Party Captain",
"Secrets of the Key",
"Shadowbeast Sighting",
"Shady Traveler",
"Shipwreck Sifters",
"Siege Zombie",
"Silver Bolt",
"Snarling Wolf",
"Soul-Guide Gryff",
"Startle",
"Stolen Vitality",
"Stormrider Spirit",
"Stuffed Bear",
"Sungold Barrage",
"Tapping at the Window",
"Tavern Ruffian",
"Thraben Exorcism",
"Timberland Guide",
"Tireless Hauler",
"Unblinking Observer",
"Unruly Mob",
"Vampire Interloper",
"Voldaren Stinger",
];

midu = [
"Ambitious Farmhand",
"Arcane Infusion",
"Baneblade Scoundrel",
"Beloved Beggar",
"Bereaved Survivor",
"Bladestitched Skaab",
"Bloodtithe Collector",
"Borrowed Time",
"Brood Weaver",
"Burly Breaker",
"Cathar's Call",
"Cathartic Pyre",
"Chaplain of Alms",
"Clear Shot",
"Contortionist Troupe",
"Corpse Cobble",
"Covert Cutpurse",
"Covetous Castaway",
"Dawnhart Mentor",
"Dawnhart Wardens",
"Deathbonnet Sprout",
"Defend the Celestus",
"Delver of Secrets",
"Devoted Grafkeeper",
"Diregraf Rebirth",
"Dissipate",
"Dreadhound",
"Dryad's Revival",
"Duelcraft Trainer",
"Fading Hope",
"Faithful Mending",
"Fangblade Brigand",
"Field of Ruin",
"Firmament Sage",
"Flame Channeler",
"Fleshtaker",
"Foul Play",
"Gavony Dawnguard",
"Ghoulish Procession",
"Grizzly Ghoul",
"Heirloom Mirror",
"Hound Tamer",
"Hungry for More",
"Infernal Grasp",
"Join the Dance",
"Kessig Naturalist",
"Loyal Gryff",
"Lunar Frenzy",
"Moonsilver Key",
"Morbid Opportunist",
"Mysterious Tome",
"Mystic Skull",
"Nebelgast Intruder",
"Necrosynthesis",
"Obsessive Astronomer",
"Odric's Outrider",
"Ominous Roost",
"Outland Liberator",
"Overwhelmed Archivist",
"Phantom Carriage",
"Play with Fire",
"Purifying Dragon",
"Rise of the Ants",
"Rite of Oblivion",
"Ritual of Hope",
"Rootcoil Creeper",
"Sacred Fire",
"Seize the Storm",
"Skaab Wrangler",
"Spellrune Painter",
"Storm Skreelix",
"Stromkirk Bloodthief",
"Sunrise Cavalier",
"Sunset Revelry",
"Thermo-Alchemist",
"Turn the Earth",
"Unnatural Moonrise",
"Vampire Socialite",
"Vengeful Strangler",
"Village Watch",
"Vivisection",
"Voldaren Ambusher",
"Winterthorn Blessing",
];

vowc = [
"Abrade",
"Adamant Will",
"Aim for the Head",
"Alchemist's Retrieval",
"Ancestral Anger",
"Apprentice Sharpshooter",
"Belligerent Guest",
"Binding Geist",
"Bleed Dry",
"Bloodcrazed Socialite",
"Blood Fountain",
"Blood Petal Celebrant",
"Blood Servitor",
"Bloody Betrayal",
"Bramble Armor",
"Ceremonial Knife",
"Chill of the Grave",
"Courier Bat",
"Cradle of Safety",
"Cruel Witness",
"Crushing Canopy",
"Dawnhart Disciple",
"Daybreak Combatants",
"Desperate Farmer",
"Diregraf Scavenger",
"Doomed Dissenter",
"Dreadlight Monstrosity",
"Drogskol Infantry",
"End the Festivities",
"Estwald Shieldbasher",
"Evolving Wilds",
"Falkenrath Celebrants",
"Fearful Villager",
"Fear of Death",
"Fierce Retribution",
"Flame-Blessed Bolt",
"Flourishing Hunter",
"Gift of Fangs",
"Gluttonous Guest",
"Grisly Ritual",
"Gryff Rider",
"Heron-Blessed Geist",
"Heron of Hope",
"Honored Heirloom",
"Hookhand Mariner",
"Hungry Ridgewolf",
"Kessig Flamebreather",
"Kindly Ancestor",
"Lacerate Flesh",
"Lantern Bearer",
"Lightning Wolf",
"Massive Might",
"Militia Rallier",
"Mindleech Ghoul",
"Moldgraf Millipede",
"Mulch",
"Nature's Embrace",
"Nebelgast Beguiler",
"Nurturing Presence",
"Parish-Blade Trainee",
"Persistent Specimen",
"Piercing Light",
"Pointed Discussion",
"Pyre Spawn",
"Ragged Recluse",
"Reckless Impulse",
"Repository Skaab",
"Rot-Tide Gargantua",
"Rural Recruit",
"Sanctify",
"Scattered Thoughts",
"Selhoff Entomber",
"Serpentine Ambush",
"Sheltering Boughs",
"Sigarda's Imprisonment",
"Skywarp Skaab",
"Snarling Wolf",
"Sporeback Wolf",
"Spore Crawler",
"Steelclad Spirit",
"Stitched Assistant",
"Supernatural Rescue",
"Sure Strike",
"Syncopate",
"Syphon Essence",
"Toxic Scorpion",
"Traveling Minister",
"Undying Malice",
"Unhallowed Phalanx",
"Unholy Officiant",
"Vampire's Kiss",
"Vampire Slayer",
"Voldaren Epicure",
"Wanderlight Spirit",
"Weary Prisoner",
"Weaver of Blossoms",
"Wedding Invitation",
"Witch's Web",
"Wolf Strike",
"Wretched Throng",
];

vowu = [
"Alluring Suitor",
"Ancient Lumberknot",
"Angelic Quartermaster",
"Archghoul of Thraben",
"Arm the Cathars",
"Ballista Watcher",
"Biolume Egg",
"Blood Hypnotist",
"Bloodsworn Squire",
"Bloodtithe Harvester",
"Boarded Window",
"Bramble Wurm",
"Bride's Gown",
"Brine Comber",
"Cartographer's Survey",
"Catapult Fodder",
"Child of the Pack",
"Circle of Confinement",
"Cloaked Cadet",
"Cobbled Lancer",
"Crawling Infestation",
"Dawnhart Geist",
"Distracting Geist",
"Diver Skaab",
"Dormant Grove",
"Dread Fugue",
"Edgar's Awakening",
"Fell Stinger",
"Fleeting Spirit",
"Foreboding Statue",
"Frenzied Devils",
"Geistlight Snare",
"Groom's Finery",
"Gryffwing Cavalry",
"Gutter Skulker",
"Hero's Downfall",
"Honeymoon Hearse",
"Infestation Expert",
"Innocent Traveler",
"Into the Night",
"Laid to Rest",
"Lambholt Raconteur",
"Lantern of the Lost",
"Lunar Rejection",
"Magma Pummeler",
"Markov Purifier",
"Markov Retribution",
"Markov Waltzer",
"Mischievous Catgeist",
"Oakshade Stalker",
"Ollenbock Escort",
"Packsong Pup",
"Panicked Bystander",
"Parasitic Grasp",
"Radiant Grace",
"Reclusive Taxidermist",
"Rending Flame",
"Resistance Squad",
"Restless Bloodseeker",
"Retrieve",
"Runebound Wolf",
"Sanguine Statuette",
"Sawblade Slinger",
"Screaming Swarm",
"Sigardian Paladin",
"Skulking Killer",
"Skull Skaab",
"Soulcipher Board",
"Spiked Ripsaw",
"Stormchaser Drake",
"Thirst for Discovery",
"Twinblade Geist",
"Undead Butler",
"Valorous Stance",
"Vampires' Vengeance",
"Vilespawn Spider",
"Voltaic Visionary",
"Wandering Mind",
"Wash Away",
"Wedding Security",
"Whispering Wizard",
"Witness the Future",
"Wolfkin Outcast",
];

neoc = [
"Akki Ember-Keeper",
"Akki Ronin",
"Akki War Paint",
"Ambitious Assault",
"Ancestral Katana",
"Armguard Familiar",
"Automated Artificer",
"Bamboo Grove Archer",
"Bearer of Memory",
"Befriending the Moths",
"Bloodfell Caves",
"Blossoming Sands",
"Brute Suit",
"Careful Cultivation",
"Chainflail Centipede",
"Clawing Torment",
"Coiling Stalker",
"Commune with Spirits",
"Crackling Emergence",
"Debt to the Kami",
"Dismal Backwater",
"Disruption Protocol",
"Dokuchi Shadow-Walker",
"Dragonfly Suit",
"Dramatist's Puppet",
"Ecologist's Terrarium",
"Eiganjo Exemplar",
"Era of Enlightenment",
"Experimental Synthesizer",
"Explosive Entry",
"Fade into Antiquity",
"Fang of Shigeki",
"Favor of Jukai",
"Futurist Sentinel",
"Geothermal Kami",
"Gift of Wrath",
"Golden-Tail Disciple",
"Grafted Growth",
"Greater Tanuki",
"Guardians of Oboro",
"Harmonious Emergence",
"Heir of the Ancient Fang",
"Imperial Oath",
"Imperial Subduer",
"Inkrise Infiltrator",
"Intercessor's Arrest",
"Iron Apprentice",
"Ironhoof Boar",
"Jukai Preserver",
"Jukai Trainee",
"Jungle Hollow",
"Kaito's Pursuit",
"Kami of Industry",
"Kami of Restless Shadows",
"Kami of Terrible Secrets",
"Kami's Flare",
"Kindled Fury",
"Kitsune Ace",
"Lethal Exploit",
"Light the Way",
"Lucky Offering",
"Master's Rebuke",
"Mirrorshell Crab",
"Mnemonic Sphere",
"Moon-Circuit Hacker",
"Moonfolk Puzzlemaker",
"Moonsnare Prototype",
"Moonsnare Specialist",
"Mothrider Patrol",
"Mukotai Ambusher",
"Network Disruptor",
"Network Terminal",
"Nezumi Bladeblesser",
"Ninja's Kunai",
"Okiba Reckoner Raid",
"Papercraft Decoy",
"Peerless Samurai",
"Planar Incision",
"Reckoner's Bargain",
"Reckoner Shakedown",
"Regent's Authority",
"Repel the Vile",
"Return to Action",
"Rugged Highlands",
"Saiba Trespassers",
"Scoured Barrens",
"Scrapyard Steelbreaker",
"Searchlight Companion",
"Season of Renewal",
"Seven-Tail Mentor",
"Short Circuit",
"Shrine Steward",
"Simian Sling",
"Skyswimmer Koi",
"Spell Pierce",
"Spirited Companion",
"Suit Up",
"Sunblade Samurai",
"Swiftwater Cliffs",
"Tales of Master Seshiro",
"Tamiyo's Compleation",
"Tamiyo's Safekeeping",
"The Modern Age",
"The Shattered States Era",
"Thornwood Falls",
"Thundersteel Colossus",
"Towashi Songshaper",
"Tranquil Cove",
"Twisted Embrace",
"Uncharted Haven",
"Undercity Scrounger",
"Unstoppable Ogre",
"Virus Beetle",
"Voltage Surge",
"Wanderer's Intervention",
"Wind-Scarred Crag",
"You Are Already Dead",
];

neou = [
"Acquisition Octopus",
"Anchor to Reality",
"Asari Captain",
"Assassin's Ink",
"Awakened Awareness",
"Azusa's Many Journeys",
"Banishing Slash",
"Behold the Unspeakable",
"Blade-Blizzard Kitsune",
"Blossom Prancer",
"Boon of Boseiju",
"Born to Drive",
"Boseiju Reaches Skyward",
"Bronze Cudgels",
"Bronzeplate Boar",
"Circuit Mender",
"Colossal Skyturtle",
"Containment Construct",
"Covert Technician",
"Discover the Impossible",
"Dockside Chef",
"Dokuchi Silencer",
"Dragonspark Reactor",
"Enormous Energy Blade",
"Enthusiastic Mechanaut",
"Essence Capture",
"Flame Discharge",
"Futurist Operative",
"Generous Visitor",
"Gloomshrieker",
"Go-Shintai of Ancient Wars",
"Go-Shintai of Boundless Vigor",
"Go-Shintai of Hidden Cruelty",
"Go-Shintai of Lost Wisdom",
"Go-Shintai of Shared Purpose",
"Gravelighter",
"Heiko Yamazaki, the General",
"High-Speed Hoverbike",
"Historian's Wisdom",
"Hotshot Mechanic",
"Imperial Recovery Unit",
"Invigorating Hot Spring",
"Jukai Naturalist",
"Kappa Tech-Wrecker",
"Kumano Faces Kakkazan",
"Leech Gauntlet",
"Life of Toshiro Umezawa",
"Malicious Malfunction",
"Mech Hangar",
"Michiko's Reign of Truth",
"Mobilizer Mech",
"Naomi, Pillar of Order",
"Nezumi Prowler",
"Norika Yamazaki, the Poet",
"Okiba Salvage",
"Oni-Cult Anvil",
"Orochi Merge-Keeper",
"Patchwork Automaton",
"Prodigy's Prototype",
"Prosperous Thief",
"Rabbit Battery",
"Reality Heist",
"Reinforced Ronin",
"Reito Sentinel",
"Replication Specialist",
"Roadside Reliquary",
"Roaring Earth",
"Runaway Trash-Bot",
"Secluded Courtyard",
"Seismic Wave",
"Selfless Samurai",
"Silver-Fur Master",
"Sky-Blessed Samurai",
"Sokenzan Smelter",
"Spinning Wheel Kick",
"Storyweave",
"Tempered in Solitude",
"The Fall of Lord Konda",
"The Long Reach of Night",
"Thirst for Knowledge",
"Touch the Spirit Realm",
"Towashi Guide-Bot",
"Twinshot Sniper",
"Unforgiving One",
"Upriser Renegade",
"Walking Skyscraper",
"Webspinner Cuff",
"When We Were Young",
];

sncc = [
"Antagonize",
"Attended Socialite",
"Backstreet Bruiser",
"Backup Agent",
"Big Score",
"Body Dropper",
"Boon of Safety",
"Botanical Plaza",
"Broken Wings",
"Brokers Hideout",
"Brokers Initiate",
"Brokers Veteran",
"Buy Your Silence",
"Cabaretti Courtyard",
"Cabaretti Initiate",
"Caldaia Strongarm",
"Capenna Express",
"Case the Joint",
"Celebrity Fencer",
"Celestial Regulator",
"Chrome Cat",
"Civic Gardener",
"Civil Servant",
"Corrupt Court Official",
"Crooked Custodian",
"Cutthroat Contender",
"Dapper Shieldmate",
"Daring Escape",
"Deal Gone Bad",
"Demon's Due",
"Dig Up the Body",
"Disdainful Stroke",
"Echo Inspector",
"Exhibition Magician",
"Expendable Lackey",
"Extract the Truth",
"Fake Your Own Death",
"For the Family",
"Gathering Throng",
"Gilded Pinions",
"Girder Goons",
"Glamorous Outlaw",
"Glittermonger",
"Goldhound",
"Halo Scarab",
"High-Rise Sawjack",
"Hold for Ransom",
"Incriminate",
"Inspiring Overseer",
"Jackhammer",
"Jetmir's Fixer",
"Jewel Thief",
"Join the Maestros",
"Kill Shot",
"Light 'Em Up",
"Maestros Initiate",
"Maestros Theater",
"Majestic Metamorphosis",
"Make Disappear",
"Masked Bandits",
"Mayhem Patrol",
"Midnight Assassin",
"Most Wanted",
"Murder",
"Obscura Initiate",
"Obscura Storefront",
"Ominous Parcel",
"Paragon of Modernity",
"Plasma Jockey",
"Prizefight",
"Psionic Snoop",
"Quick-Draw Dagger",
"Racers' Ring",
"Raffine's Guidance",
"Raffine's Informant",
"Rakish Revelers",
"Ready to Rumble",
"Revelation of Power",
"Revel Ruiner",
"Rhox Pummeler",
"Riveteers Initiate",
"Riveteers Overlook",
"Rooftop Nuisance",
"Run Out of Town",
"Security Bypass",
"Sewer Crocodile",
"Shattered Seraph",
"Skybridge Towers",
"Sky Crier",
"Snooping Newsie",
"Social Climber",
"Spara's Adjudicators",
"Speakeasy Server",
"Sticky Fingers",
"Strangle",
"Tramway Station",
"Warm Welcome",
"Waterfront District",
"Witness Protection",
"Witty Roastmaster",
"Wrecking Crew",
];

sncu = [
"A Little Chat",
"Angelic Observer",
"An Offer You Can't Refuse",
"Arc Spitter",
"Ballroom Brawlers",
"Bouncer's Beatdown",
"Brass Knuckles",
"Brazen Upstart",
"Brokers Charm",
"Cabaretti Charm",
"Call In a Professional",
"Cement Shoes",
"Ceremonial Groundbreaker",
"Citizen's Crowbar",
"Cleanup Crew",
"Cormela, Glamour Thief",
"Corpse Appraiser",
"Courier's Briefcase",
"Crew Captain",
"Darling of the Masses",
"Disciplined Duelist",
"Dusk Mangler",
"Elegant Entourage",
"Exotic Pets",
"Faerie Vandal",
"Fatal Grudge",
"Forge Boss",
"Freelance Muscle",
"Glittering Stockpile",
"Graveyard Shift",
"Grisly Sigil",
"Hypnotic Grifter",
"Illicit Shipment",
"Illuminator Virtuoso",
"Involuntary Employment",
"Knockout Blow",
"Lagrella, the Magpie",
"Luxurious Libation",
"Maestros Charm",
"Mage's Attendant",
"Metropolis Angel",
"Mr. Orfeo, the Boulder",
"Night Clubber",
"Nimble Larcenist",
"Obscura Charm",
"Out of the Way",
"Patch Up",
"Psychic Pickpocket",
"Public Enemy",
"Pugnacious Pugilist",
"Pyre-Sledge Arsonist",
"Queza, Augur of Agonies",
"Raffine's Silencer",
"Refuse to Yield",
"Riveteers Charm",
"Riveteers Decoy",
"Riveteers Requisitioner",
"Rob the Archives",
"Rocco, Cabaretti Caterer",
"Rogues' Gallery",
"Rumor Gatherer",
"Scuttling Butler",
"Security Rhox",
"Sizzling Soloist",
"Sleep with the Fishes",
"Slip Out the Back",
"Stimulus Package",
"Suspicious Bookcase",
"Swooping Protector",
"Syndicate Infiltrator",
"Tainted Indulgence",
"Take to the Streets",
"Tavern Swindler",
"Torch Breath",
"Unlucky Witness",
"Vampire Scrivener",
"Venom Connoisseur",
"Voice of the Vermin",
"Whack",
"Wingshield Agent",
];